# default rules are in templates/kubelet.rules.yaml
# prometheusRules: {}

## Custom Labels to be added to ServiceMonitor
##
additionalServiceMonitorLabels: {}
##Custom Labels to be added to Prometheus Rules ConfigMap
##
additionalRulesConfigMapLabels: {}
