apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "prometheus"
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    prometheus: {{ .Release.Name }}
    release: {{ .Release.Name }}
    role: alert-rules
    {{- if .Values.additionalRulesConfigMapLabels }}
{{ toYaml .Values.additionalRulesConfigMapLabels | indent 4 }}
    {{- end }}    
  name: {{ template "exporter-telexporter.fullname" . }}
data:
{{- if .Values.prometheusRules }}
{{- $root := . }}
{{- range $key, $val := .Values.prometheusRules }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
{{ else }}
  agent.rules: |-
    {{- include "agent.rules.yaml.tpl" . | indent 4}}
  alcide-infra.rules: |-
    {{- include "alcide-infra.rules.yaml.tpl" . | indent 4}}
  monitors.rules: |-
    {{- include "monitors.rules.yaml.tpl" . | indent 4}}
  server.rules: |-
    {{- include "server.rules.yaml.tpl" . | indent 4}}
{{ end }}
