apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: "prometheus"
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    prometheus: {{ .Release.Name }}
    release: {{ .Release.Name }}
    role: alert-rules
  name: {{ template "exporter-telexporter.fullname" . }}
spec:
  groups:
  {{- include "agent.rules.yaml.tpl" . | indent 2}}
  {{- include "alcide-infra.rules.yaml.tpl" . | indent 2}}
  {{- include "monitors.rules.yaml.tpl" . | indent 2}}
  {{- include "server.rules.yaml.tpl" . | indent 2}}
  {{- include "reputation.rules.yaml.tpl" . | indent 2}}