apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: "prometheus"
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    prometheus: {{ .Release.Name }}
    release: {{ .Release.Name }}
    role: alert-rules
  name: {{ template "exporter-telexporter.fullname" . }}
data:
  agent.rules: |-
    {{- include "agent.rules.yaml.tpl" . | indent 4}}
  alcide-infra.rules: |-
    {{- include "alcide-infra.rules.yaml.tpl" . | indent 4}}
  monitors.rules: |-
    {{- include "monitors.rules.yaml.tpl" . | indent 4}}
  server.rules: |-
    {{- include "server.rules.yaml.tpl" . | indent 4}}
