apiVersion: {{ template "prometheus-operator.apiVersion" . }}
kind: ServiceMonitor
metadata:
  labels:
    app: {{ template "exporter-telexporter.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: telexporter
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    prometheus: {{ .Release.Name }}
  name: {{ template "exporter-telexporter.fullname" . }}
spec:
  selector:
    matchLabels:
      metrics: alcide
  endpoints:
  - port: http
    interval: 10s
  namespaceSelector:
    matchNames:
    - alcide