{
 "title": "Agents",
 "tags": [
  "Alcide",
  "Agent"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Agents Console Errors By Topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*_agent.*._trace_.*._error_count\"} > 0"
    }
   ]
  },
  {
   "title": "Agent -  Density : Go Routines Ratio",
   "type": "graph",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+_agent_daemon_runtime_NumGoroutine\"}/({__name__=~\".+agent_dataplane_workload_density_count\"} + {__name__=~\".+agent_dataplane_compute_density_count\"})"
    }
   ]
  },
  {
   "title": "Workload Bind Time (99Percentile)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ms", "label": "Bind Duration" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+agent_agent_dataplane_workload_successful_bind_duration\",type=\"perc99\"}"
    }
   ]
  },
  {
   "title": "Workload Bind Time (99Percentile)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ms", "label": "Bind Duration" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+agent_agent_dataplane_workload_successful_bind_duration\",type=\"perc99\"}"
    }
   ]
  },
  {
   "title": "Daemon - Go Routines",
   "type": "graph",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+_agent_daemon_runtime_NumGoroutine\"}"
    }
   ]
  },
  {
   "title": "Workload Density",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+_dataplane_workload_density_count\"}"
    }
   ]
  },
  {
   "title": "Topology Errors",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+_agent_daemon_trace_topology_error_count\"}",
     "legendFormat": "{{source}}"
    }
   ]
  }
 ]
}