{
 "title": "Cassandra",
 "tags": [
  "Ops",
  "Cassandra",
  "Alcide"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cassandra_index",
    "label": "Cassandra Index",
    "query": "label_values(cassandra_cache_requests_total,pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cassandra Disk Usage",
   "type": "graph",
   "description": "Cassandra Persistent Volume used disk space",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*$cassandra_index.*\"}"
    }
   ]
  },
  {
   "title": "Read Latency In Micro Seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "cassandra_table_readlatency_all{quantile=\"0.95\",pod=~\".*$cassandra_index.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Write Latency In Micro Seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "cassandra_table_writelatency_all{quantile=\"0.95\",pod=~\".*$cassandra_index.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Client Request Read Latency In Micro Seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "cassandra_clientrequest_latency_read{quantile=\"0.95\",pod=~\".*$cassandra_index.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Client Request Write Latency In Micro Seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "cassandra_clientrequest_latency_write{quantile=\"0.95\",pod=~\".*$cassandra_index.*\"}",
     "legendFormat": "POD: {{pod}} Quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_cache_hitrate{cache=\"chunkcache\",pod=~\".*$cassandra_index.*\"}",
     "legendFormat": "POD: {{pod}} Chunkcache "
    },
    {
     "expr": "cassandra_cache_hitrate{cache=\"countercache\",pod=~\".*$cassandra_index.*\"}",
     "legendFormat": "POD: {{pod}} CounterCache "
    },
    {
     "expr": "cassandra_cache_hitrate{cache=\"keycache\",pod=~\".*$cassandra_index.*\"}",
     "legendFormat": "POD:  {{pod}} KeyCache"
    },
    {
     "expr": "cassandra_cache_hitrate{cache=\"rowcache\",pod=~\".*$cassandra_index.*\"}",
     "legendFormat": "POD:  {{pod}} RowCache"
    }
   ]
  },
  {
   "title": "Client Request RangeSlice Latency In Micro Seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "cassandra_clientrequest_latency_rangeslice{quantile=\"0.95\",pod=~\".*$cassandra_index.*\"}",
     "legendFormat": "POD: {{pod}} Quantile: {{quantile}}"
    }
   ]
  }
 ]
}