{
 "title": "Kafka Overview",
 "description": "Kafka resource usage and throughput",
 "tags": [
  "Ops",
  "Kafka",
  "Alcide"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "kafka_index",
    "label": "Kafka Index",
    "query": "label_values(kafka_server_sessionexpirelistener_zookeeperauthfailures_total,pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{pod=~\".*$kafka_index.*\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{pod=~\".*$kafka_index.*\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{pod=~\".*$kafka_index.*\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_messagesin_total{pod=~\".*$kafka_index.*\",topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesin_total{pod=~\".*$kafka_index.*\",topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesout_total{pod=~\".*$kafka_index.*\",topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka Disk Usage",
   "type": "graph",
   "description": "Kafka Persistent Volume used disk space",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*$kafka_index.*\"}"
    }
   ]
  },
  {
   "title": "netactivityLag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Lag" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroup_lag{topic=\"netactivity\",consumergroup!~\".*e2e.*\"}",
     "legendFormat": "{{topic}}:{{consumergroup}}:{{partition}}"
    }
   ]
  },
  {
   "title": "netactivity-lag-rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Lag" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_consumergroup_lag{topic=\"netactivity\",consumergroup!~\".*e2e.*\"}[5m])",
     "legendFormat": "{{topic}}:{{consumergroup}}:{{partition}}"
    }
   ]
  },
  {
   "title": "inventoryLag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Lag" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroup_lag{topic=\"inventory\",consumergroup!~\".*e2e.*\"}",
     "legendFormat": "{{topic}}:{{consumergroup}}:{{partition}}"
    }
   ]
  },
  {
   "title": "inventory-lag-rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Lag" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_consumergroup_lag{topic=\"inventory\",consumergroup!~\".*e2e.*\"}[5m])",
     "legendFormat": "{{topic}}:{{consumergroup}}:{{partition}}"
    }
   ]
  },
  {
   "title": "componentsActivityLag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Lag" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroup_lag{topic=\"components-activity\",consumergroup!~\".*e2e*.\"}",
     "legendFormat": "{{topic}}:{{consumergroup}}:{{partition}}"
    }
   ]
  },
  {
   "title": "SumBytesInByBroker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "decbytes", "label": "bytesTotal" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesin_total) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "SumBytesOutByBroker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "decbytes", "label": "BytesTotal" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesout_total) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "components-activity-lag-rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "Lag" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_consumergroup_lag{topic=\"components-activity\",consumergroup!~\".*e2e*.\"}[5m])",
     "legendFormat": "{{topic}}:{{consumergroup}}:{{partition}}"
    }
   ]
  },
  {
   "title": "InSyncReplicaCount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "BrokerCount" }
   ],
   "targets": [
    {
     "expr": "kafka_cluster_partition_insyncreplicascount{topic!~\"__consumer_offsets\"}",
     "legendFormat": "{{topic}}:{{partition}}"
    }
   ]
  },
  {
   "title": "UnderReplicatedPartitions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "OutOfISR" }
   ],
   "targets": [
    {
     "expr": "kafka_cluster_partition_underreplicated{topic!~\"__consumer_offsets\"}",
     "legendFormat": "{{topic}}:{{partition}}"
    }
   ]
  }
 ]
}