{
 "title": "Monitors",
 "tags": [
  "Alcide",
  "Monitor"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Kubemon, Awsmon Error Logs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*system:.*k8smonitor.*trace.*_error_count\"}"
    }
   ]
  },
  {
   "title": "Cloud Watchdog - API Errors",
   "type": "graph",
   "description": "CLoud Provider API Errors",
   "gridPos": { "h": 6, "w": 11, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+cloudwatchdog_cloudprovider_.*_api_request_errors\"}"
    }
   ]
  },
  {
   "title": "K8S Monitor - Inventory Send Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+K8SMonitor_kafka_record_send_rate_for_topic_inventory\",type=\"rate5\"}"
    }
   ]
  },
  {
   "title": "Cloud Watchdog - Upstream Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Error rate" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+cloudwatchdog_.*._.*._error\", type=\"rate5\"}"
    }
   ]
  },
  {
   "title": "AWS monitors send rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+AWS.*_kafka_record_send_rate_for_topic_inventory\",type=\"rate5\"}"
    }
   ]
  },
  {
   "title": "Cloud Watchdog - API Duration (Perc99)",
   "type": "graph",
   "description": "CLoud Provider API request duration",
   "gridPos": { "h": 7, "w": 11, "x": 10, "y": 13 },
   "yaxes": [
    { "format": "ms", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+cloudwatchdog_cloudprovider_.*_api_request_duration_ms\", type=\"perc99\"}"
    }
   ]
  },
  {
   "title": "Cloud Watchdog - Upstream Inventory Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none", "label": "Event Rate" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+cloudwatchdog_kafka_record_send_rate_for_topic_inventory\", type=\"rate5\"}"
    }
   ]
  },
  {
   "title": "Kubmon  and Awsmon Warning logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 10, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*system:.*k8smonitor.*trace.*_warn_count\"}"
    },
    {
     "expr": "{__name__=~\".*system:.*AWS.*trace.*_warn_count\"}"
    }
   ]
  }
 ]
}