{
 "title": "Cluster Persistent Volumes",
 "tags": [
  "Ops",
  "PVC"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "kafka_index",
    "label": "Kafka Index",
    "query": "label_values(kafka_cluster_partition_replicascount,pod)"
   },
   {
    "name": "cassandra_index",
    "label": "Cassandra Index",
    "query": "label_values(cassandra_cache_requests_total,pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cassandra Disk Usage Percentage",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*$cassandra_index.*\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*$cassandra_index.*\"} * 100"
    }
   ]
  },
  {
   "title": "Kafka Disk Usage Percentage",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*$kafka_index.*\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*$kafka_index.*\"} * 100"
    }
   ]
  },
  {
   "title": "Etcd Disk Usage Percentage",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*etcd.*\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*etcd.*\"} * 100"
    }
   ]
  },
  {
   "title": "ZooKeeper Disk Usage Percentage",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*zookeeper.*\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*zookeeper.*\"} * 100"
    }
   ]
  },
  {
   "title": "Persistent Volume Claims Disk Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes"
    }
   ]
  }
 ]
}