{
 "title": "Reputation",
 "description": "Reputation Feeds aka Diana",
 "tags": [
  "Reputation",
  "Diana"
 ],
 "time": { "from": "now/w", "to": "now" },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "content": "# Reputation Fetcher" },
  {
   "title": "Reputation Fetcher (Warnings)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*reputation_monitor_trace_fetcher_.*_warn_count\"}"
    }
   ]
  },
  {
   "title": "Reputation Fetcher (Error)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*reputation_monitor_trace_fetcher_.*_error_count\"}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 11 }, "content": "# Reputation Transformer" },
  {
   "title": "Reputation Transformer (Warnings)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*reputation_monitor_trace_reputation_.*_warn_count\"}"
    }
   ]
  },
  {
   "title": "Reputation Transformer (Error)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*reputation_monitor_trace_reputation_.*_error_count\"}"
    }
   ]
  }
 ]
}