{
 "title": "Server Processes",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "GraphQL requests rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "per Sec" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+GraphQLExecutorImpl_requestsRate\", type=\"rate5\"}",
     "legendFormat": "{{source}} "
    }
   ]
  },
  {
   "title": "GraphQL requests latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "MSec" }
   ],
   "targets": [
    {
     "expr": "max({__name__=~\".+GraphQLExecutorImpl_requestsRate\", type=\"max\"})",
     "legendFormat": "max"
    },
    {
     "expr": "max({__name__=~\".+GraphQLExecutorImpl_requestsRate\", type=\"perc99\"})",
     "legendFormat": "99%"
    },
    {
     "expr": "max({__name__=~\".+GraphQLExecutorImpl_requestsRate\", type=\"perc95\"})",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "GraphQL errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+GraphQLExecutorImpl_errors\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Inventory events rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "per Sec" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+InventoryEventsProcessorImpl_eventsRate\", type=\"rate5\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Inventory events latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "MSec" }
   ],
   "targets": [
    {
     "expr": "max({__name__=~\".+InventoryEventsProcessorImpl_eventsRate\", type=\"max\"})",
     "legendFormat": "max"
    },
    {
     "expr": "max({__name__=~\".+InventoryEventsProcessorImpl_eventsRate\", type=\"perc99\"})",
     "legendFormat": "99%"
    },
    {
     "expr": "max({__name__=~\".+InventoryEventsProcessorImpl_eventsRate\", type=\"perc95\"})",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "Inventory events errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+InventoryEventsProcessorImpl_errors\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Activity events rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "per Sec" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+ActivityEventsProcessorImpl_eventsRate\", type=\"rate5\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Activity events latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "MSec" }
   ],
   "targets": [
    {
     "expr": "max({__name__=~\".+ActivityEventsProcessorImpl_eventsRate\", type=\"max\"})",
     "legendFormat": "max"
    },
    {
     "expr": "max({__name__=~\".+ActivityEventsProcessorImpl_eventsRate\", type=\"perc99\"})",
     "legendFormat": "99%"
    },
    {
     "expr": "max({__name__=~\".+ActivityEventsProcessorImpl_eventsRate\", type=\"perc95\"})",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "Activity events errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+ActivityEventsProcessorImpl_errors\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Alert events rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "per Sec" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+AlertLogEventsProcessorImpl_eventsRate\", type=\"rate5\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Alert events latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "MSec" }
   ],
   "targets": [
    {
     "expr": "max({__name__=~\".+AlertLogEventsProcessorImpl_eventsRate\", type=\"max\"})",
     "legendFormat": "max"
    },
    {
     "expr": "max({__name__=~\".+AlertLogEventsProcessorImpl_eventsRate\", type=\"perc99\"})",
     "legendFormat": "99%"
    },
    {
     "expr": "max({__name__=~\".+AlertLogEventsProcessorImpl_eventsRate\", type=\"perc95\"})",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "Alert events errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+AlertLogEventsProcessorImpl_errors\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Security features events rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "per Sec" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+SecurityFeaturesProcessorImpl_eventsRate\", type=\"rate5\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Security features events latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "MSec" }
   ],
   "targets": [
    {
     "expr": "max({__name__=~\".+SecurityFeaturesProcessorImpl_eventsRate\", type=\"max\"})",
     "legendFormat": "max"
    },
    {
     "expr": "max({__name__=~\".+SecurityFeaturesProcessorImpl_eventsRate\", type=\"perc99\"})",
     "legendFormat": "99%"
    },
    {
     "expr": "max({__name__=~\".+SecurityFeaturesProcessorImpl_eventsRate\", type=\"perc95\"})",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "Security features events errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+SecurityFeaturesProcessorImpl_errors\"}",
     "legendFormat": "{{source}} processing"
    },
    {
     "expr": "{__name__=~\".+SecurityAlertsStreamWriterImpl_errors\"}",
     "legendFormat": "{{source}} write"
    }
   ]
  },
  {
   "title": "Alert level events rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short", "label": "per Sec" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+EntitiesAlertLevelEventsProcessorImpl_eventsRate\", type=\"rate5\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Security beliefs cache",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+SecurityFeaturesProcessorImplCache.loads\"}",
     "legendFormat": "{{source}} loads"
    },
    {
     "expr": "{__name__=~\".+SecurityFeaturesProcessorImplCache.evictions\"}",
     "legendFormat": "{{source}} evictions"
    }
   ]
  },
  {
   "title": "Alert level events errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+EntitiesAlertLevelEventsProcessorImpl_errors\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "WebSocket notifications rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short", "label": "per Sec" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+NotificationTaskImpl_webSocket_notifications\", type=\"rate5\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Alert level updates rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 54 },
   "yaxes": [
    { "format": "short", "label": "per Sec" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+AlertLevelUpdateEventsProcessorImpl_eventsMeter\", type=\"rate5\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "WebSocket notifications errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+NotificationTaskImpl_webSocket_errors\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Metrics events rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short", "label": "per Sec" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+MetricsEventsProcessorImpl_eventsRate\", type=\"rate5\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Metrics events latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 63 },
   "yaxes": [
    { "format": "short", "label": "MSec" }
   ],
   "targets": [
    {
     "expr": "max({__name__=~\".+MetricsEventsProcessorImpl_eventsRate\", type=\"max\"})",
     "legendFormat": "max"
    },
    {
     "expr": "max({__name__=~\".+MetricsEventsProcessorImpl_eventsRate\", type=\"perc99\"})",
     "legendFormat": "99%"
    },
    {
     "expr": "max({__name__=~\".+MetricsEventsProcessorImpl_eventsRate\", type=\"perc95\"})",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "Metrics events errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+MetricsEventsProcessorImpl_errors\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Audit events rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short", "label": "per Sec" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+AuditEventsProcessorImpl_eventsRate\", type=\"rate5\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Audit events latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 72 },
   "yaxes": [
    { "format": "short", "label": "MSec" }
   ],
   "targets": [
    {
     "expr": "max({__name__=~\".+AuditEventsProcessorImpl_eventsRate\", type=\"max\"})",
     "legendFormat": "max"
    },
    {
     "expr": "max({__name__=~\".+AuditEventsProcessorImpl_eventsRate\", type=\"perc99\"})",
     "legendFormat": "99%"
    },
    {
     "expr": "max({__name__=~\".+AuditEventsProcessorImpl_eventsRate\", type=\"perc95\"})",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "Audit events errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+AuditEventsProcessorImpl_errors\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Exported events rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short", "label": "per Sec" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+ExportEventsProcessorImpl_eventsRate\", type=\"rate5\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Exported events latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 81 },
   "yaxes": [
    { "format": "short", "label": "MSec" }
   ],
   "targets": [
    {
     "expr": "max({__name__=~\".+ExportEventsProcessorImpl_eventsRate\", type=\"max\"})",
     "legendFormat": "max"
    },
    {
     "expr": "max({__name__=~\".+ExportEventsProcessorImpl_eventsRate\", type=\"perc99\"})",
     "legendFormat": "99%"
    },
    {
     "expr": "max({__name__=~\".+ExportEventsProcessorImpl_eventsRate\", type=\"perc95\"})",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "Exported events errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+ExportEventsProcessorImpl_errors\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Cassandra queries rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short", "label": "per Sec" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+io_alcide_log_db_DbStoreImpl_queries\", type=\"rate5\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Cassandra queries latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 90 },
   "yaxes": [
    { "format": "short", "label": "MSec" }
   ],
   "targets": [
    {
     "expr": "max({__name__=~\".+DbStoreImpl_queries\", type=\"max\"})",
     "legendFormat": "max"
    },
    {
     "expr": "max({__name__=~\".+DbStoreImpl_queries\", type=\"perc99\"})",
     "legendFormat": "99%"
    },
    {
     "expr": "max({__name__=~\".+DbStoreImpl_queries\", type=\"perc95\"})",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "Cassandra errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+DbStoreImpl_errors\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Cassandra inserts rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "short", "label": "per Sec" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+DbStoreImpl_inserts\", type=\"rate5\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Cassandra inserts latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 99 },
   "yaxes": [
    { "format": "short", "label": "MSec" }
   ],
   "targets": [
    {
     "expr": "max({__name__=~\".+DbStoreImpl_inserts\", type=\"max\"})",
     "legendFormat": "max"
    },
    {
     "expr": "max({__name__=~\".+DbStoreImpl_inserts\", type=\"perc99\"})",
     "legendFormat": "99%"
    },
    {
     "expr": "max({__name__=~\".+DbStoreImpl_inserts\", type=\"perc95\"})",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "Ignite errors rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 99 },
   "yaxes": [
    { "format": "short", "label": "per Sec" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+ignite.+Appender_error\", type=\"rate5\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Threads count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+JVM_Threads_count\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 108 },
   "yaxes": [
    { "format": "short", "label": "ratio" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+JVM_Memory_heap_usage\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "File descriptors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 108 },
   "yaxes": [
    { "format": "short", "label": "ratio" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+JVM_file_descriptors\"}",
     "legendFormat": "{{source}}"
    }
   ]
  }
 ]
}