{{- if not .Values.configFromSecret }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    alertmanager: {{ .Release.Name }}
    app: {{ template "alertmanager.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: alertmanager-{{ .Release.Name }}
data:
{{ if eq .Values.envType "internal" }}
  alertmanager.yaml: {{ toYaml .Values.internalConfig | b64enc | quote }}
{{ else if eq .Values.envType "production" }}
  alertmanager.yaml: {{ toYaml .Values.productionConfig | b64enc | quote }}
{{- end }}

{{- range $key, $val := .Values.templateFiles }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
{{- end }}
